### ISSUE TITLE
Drupal 10 support

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_outpost#5]
Just testing with Drupal 10 for Greenwich and I've upgraded the site. 

I managed to uninstall localgov_direcotries and localgov_outpost and re-install to check that worked.

Created a Directory channel with Outpost endpoint.

run 

```
ddev drush ms 
```

And get this error: 

```
Entity queries must explicitly set whether the query should be access checked or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck().   
```

I can't seem to find an entityQuery in the modules, so not sure where we need to add an accessCheck().

@ekes any ideas?

**Comment by finnlewis** [comment]
Doh - found it! 

https://github.com/localgovdrupal/localgov_outpost/blob/1.x/modules/localgov_outpost_connector/src/Plugin/MigrationDeriver.php#L53-L57

**Comment by finnlewis** [comment]
With the #6 the migration seems to work on Drupal 10. :smile: 

The locations are not being migrated in yet, but they were also not being migrated in yet on Drupal 9

**Comment by finnlewis** [comment]
I guess we will want to update the migrations to target geo_entity rather than localgov_geo:

https://github.com/localgovdrupal/localgov_outpost/blob/1.x/modules/localgov_outpost_connector/config/migration_base/migration.localgov_outpost_locations.yml#L71

**Comment by ekes** [comment]
location (and category) fixed https://github.com/localgovdrupal/localgov_outpost/commit/3c9959ec110a36091fec7aac5820f045e9fd1fb7 (both branches) 
Update location importer for D10 geo entity https://github.com/localgovdrupal/localgov_outpost/commit/3f4db3f0ebecbf1d4c429c585f558aa224d7eb97 (just this branch)

Suggesting renaming this feature branch to `2.x`. It'd be nice not to have to maintain `1.x` further, but for now I'll keep adding features to both.

**Comment by ekes** [comment]
Made a `2.x` branch.
